#!/usr/bin/env node
// Copies contract ABIs from Foundry's build output into api/src/chain/abis.ts so viem can infer
// types. Run after changing contracts:  pnpm contracts:build && pnpm --filter @mohar/api abi
// No dependencies on purpose: CI runs it in the contracts job with plain Node.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const contracts = [
  ["MoharToken", "moharTokenAbi"],
  ["WalletRegistry", "walletRegistryAbi"],
  ["ReserveRegistry", "reserveRegistryAbi"],
  ["MockV3Aggregator", "mockV3AggregatorAbi"],
];

let out =
  "// GENERATED by api/scripts/extract-abis.mjs from contracts/out — do not edit by hand.\n" +
  "// Regenerate: pnpm contracts:build && pnpm --filter @mohar/api abi\n";
for (const [name, exportName] of contracts) {
  const artifact = JSON.parse(
    readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8"),
  );
  out += `\nexport const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}
writeFileSync(join(root, "api", "src", "chain", "abis.ts"), out);
console.log(`Wrote ABIs for ${contracts.map(([n]) => n).join(", ")}`);
